Repository ssbc/patchwork, pull requests merged in 2019-08, with the labels that each got.

#1152 Make feed deletion an opt-in setting
  lib/depject/page/html/render/settings.js
  lib/main-window.js
  locales/en.json
  package-lock.json
  package.json
Labels: type:enhancement

#1158 Refactor to remove bulk-require module
  lib/depject/index.js
  package-lock.json
  package.json
Labels: type:enhancement

#1155 Add changelog entries to release notes
  docs/release-notes-template.md
  scripts/release-notes.js
Labels: type:enhancement

#1162 Fix depject with bulk-require tree
  lib/depject/index.js
Labels: type:bug

#1166 allow "Copy Message Text" on gatherings
  lib/context-menu-and-spellcheck.js
  lib/main-window.js
Labels: topic:UX & UI, type:bug

#1167 fix showing gatherings in feed when first created
  lib/plugins/gatherings.js
Labels: topic:UX & UI, type:bug

#1168 Upgrade deps, mostly for ssb-markdown
  lib/catch-links.js
  lib/depject/contact/html/follow-toggle.js
  lib/depject/message/async/publish.js
  lib/depject/tag/html/tag.js
  lib/main-window.js
  lib/plugins/backlinks.js
  lib/plugins/channel-feed.js
  lib/plugins/contacts.js
  lib/plugins/likes.js
  lib/plugins/mentions-feed.js
  lib/plugins/private-feed.js
  lib/plugins/subscriptions2.js
  package-lock.json
  package.json
Labels: type:enhancement

#1169 Fix profile preview for encoded hashtags
  lib/depject/channel/html/preview.js
  package-lock.json
Labels: type:bug

#1171 Fix URI decode error breaking messages
  lib/catch-links.js
Labels: type:bug

#1172 Downgrade ssb-legacy-conn to 1.x.x
  package-lock.json
  package.json
Labels: type:bug

#1106 feat: re-enable ssb-ebt
  lib/plugins/index.js
  lib/server-process.js
  package-lock.json
  package.json
Labels: topic:performance, type:enhancement
