Repository ssbc/patchwork, pull requests merged in 2019-12, with the labels that each got.

#1211 Add Homebrew instructions to readme
  README.md
Labels: type:enhancement

#1219 Add support for SSB Rooms
  index.js
  lib/depject/invite/invite.js
  lib/depject/invite/sheet.js
  lib/depject/page/html/render/public.js
  lib/plugins/index.js
  lib/server-process.js
  locales/en.json
  package-lock.json
  package.json
Labels: type:enhancement

#1227 Feature: Localize timestamps and "time ago" with moment
  lib/depject/index.js
  lib/depject/intl/sync/i18n.js
  lib/depject/lib/timeAgo.js
  lib/depject/message/html/render/gathering.js
  lib/depject/message/html/timestamp.js
  lib/main-window.js
  locales/de.json
  locales/el.json
  locales/en.json
  locales/eo.json
  locales/es.json
  locales/fr.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt.json
  locales/ru.json
  locales/sk.json
  locales/sl.json
  locales/uk.json
  locales/ur.json
  locales/zh-CN.json
  locales/zh-TW.json
  package-lock.json
  package.json
Labels: topic:i18n

#1218 Add sandbox documentation
  docs/INSTALL.md
  docs/release-notes-template.md
Labels: type:enhancement

#1228 Change to throttle sidebar UI on public page
  lib/depject/page/html/render/public.js
Labels: type:bug

#1229 Add ia32 build target
  package.json
Labels: type:enhancement
