Repository ssbc/patchwork, pull requests merged in 2019-04, with the labels that each got.

#937 Add a confirmation of clearing your draft.
  locales/en.json
  modules/message/html/compose.js
Labels: enhancement

#975 Update npm dependencies
  package-lock.json
  package.json
  server-process.js
Labels: enhancement

#981 Fix .travis.yml and lint code
  .travis.yml
  lib/context-menu-and-spellcheck.js
  modules/app/html/search.js
  modules/message/html/compose.js
  modules/sbot.js
Labels: enhancement

#987 Fix date picker, downgrade to last working version
  modules/gathering/sheet/edit.js
  package-lock.json
  package.json
Labels: bug

#984 Only show search in the context menu when relevant
  lib/context-menu-and-spellcheck.js
Labels: enhancement

#988 Set Windows port correctly
  index.js
Labels: bug

#974 Use read-only mode while indexing
  locales/en.json
  modules/app/html/progress-notifier.js
  modules/sbot.js
Labels: enhancement

#994 Release 3.12.0-alpha.1
  .dockerignore
  .gitignore
  .travis.yml
  build/background.png
  build/background@2x.png
  build/dmg-icon.icns
  build/icon.icns
  build/icon.ico
  build/icon.svg
  build/setup-icon.ico
  lib/catch-links.js
  package-lock.json
  package.json
Labels: builds, enhancement

#997 Use default SSBC stale settings
  .github/stale.yml
Labels: enhancement

#1001 Fix private err
  package-lock.json
  package.json
  sbot/private-feed.js
Labels: bug

#1003 Fix DuckDuckGo search on spellcheck context menu
  lib/context-menu-and-spellcheck.js
Labels: bug

#1004 Use electron-builder defaults
  build/dmg/icon.icns
  build/installerIcon.ico
  package.json
Labels: enhancement

#1005 Pretty-print redacted config with `console.dir`
  index.js
Labels: enhancement

#1006 Stop sending console output to both terminals
  assets/base.html
Labels: bug

#1007 Deduplicate style code
  styles/dark/index.js
  styles/index.js
  styles/light/index.js
  styles/vendor.js
Labels: enhancement

#1010 Fix lockfile and undo `npm dedupe`
  package-lock.json
Labels: bug

#1012 Revert "Stop sending console output to both terminals"
  assets/base.html
Labels: bug
