Repository ssbc/patchwork, pull requests merged in 2019-06, with the labels that each got.

#1054 Replace emoji symlink with real path
  CHANGELOG.md
  assets/img/emoji
  modules/emoji.js
Labels: bug

#1081 fix isPrivate count check
  modules/message/sheet/preview.js
Labels: bug

#1085 chore: have Travis only build `master`
  .travis.yml
Labels: topic:builds, topic:performance, type:enhancement

#1064 Simple readme
  CONTRIBUTING.md
  INSTALL.md
  README.md
  code-of-conduct.md
  package.json
Labels: type:enhancement

#1086 chore: update node dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: type:enhancement

#1090 fix: ensure code blocks aren't cropped
  styles/base/markdown.mcss
Labels: topic:UX & UI, type:enhancement

#1084 feat: retry update check every 24 hours
  lib/latest-update.js
  lib/main-window.js
Labels: topic:builds, type:enhancement

#1094 feat: improve emoji support
  .vscode/settings.json
  lib/depject/emoji.js
  lib/depject/message/html/markdown.js
  lib/depject/message/sheet/preview.js
  lib/depject/suggest.js
  lib/main-window.js
  package-lock.json
  package.json
  styles/base/base.mcss
  styles/base/markdown.mcss
Labels: topic:UX & UI, type:enhancement

#1098 fix: clear update interval correctly
  lib/latest-update.js
Labels: type:bug

#1099 feat: render more than one large emoji
  lib/depject/message/html/markdown.js
Labels: type:enhancement

#1096 fix: log when Patchwork is already running
  index.js
Labels: type:bug

#1097 fix: reverse backward hidden dialog logic
  lib/latest-update.js
Labels: type:bug

#1100 fix: workaround bug where node-emoji returns extra colons
  lib/depject/message/html/markdown.js
Labels: topic:UX & UI, type:bug

#1101 Use system font
  lib/main-window.js
  styles/base/base.mcss
  styles/base/main-window.mcss
Labels: topic:UX & UI, type:enhancement

#1095 feat: add script to output release notes
  docs/release-notes-template.md
  package.json
  scripts/release-notes.js
Labels: type:documentation, type:enhancement

#1113 Fix typo
  locales/es.json
Labels: type:bug

#1117 Update Spanish translation
  locales/es.json
Labels: topic:UX & UI, type:enhancement

#1115 build: clarify support for Node.js Active LTS
  .travis.yml
  docs/INSTALL.md
Labels: topic:builds, topic:documentation, type:enhancement

#1105 refactor: encode emoji suggestion as character, not shortcode
  lib/depject/suggest.js
Labels: topic:UX & UI, type:enhancement

#1120 Not typewriter font plz
  styles/base/compose.mcss
Labels: type:bug

#1126 Add Esperanto translation
  locales/en.json
  locales/eo.json
Labels: topic:UX & UI, type:enhancement

#1026 Add feed deletion
  lib/main-window.js
  lib/server-process.js
  package-lock.json
  package.json
Labels: type:enhancement

#1122 refactor: remove dead code and avoid `undefined`
  lib/context-menu-and-spellcheck.js
  lib/depject/backlinks/obs.js
  lib/depject/contact/obs.js
  lib/depject/message/html/markdown.js
  lib/depject/suggest.js
  lib/lookup-roots.js
  lib/mutant-pull-dict.js
  lib/mutant-pull-value.js
  lib/plugins/channel-feed.js
  lib/plugins/likes.js
  lib/plugins/private-feed.js
  lib/plugins/recent-feeds.js
  lib/plugins/thread.js
  lib/scroller.js
  lib/thread-summary.js
  package-lock.json
  package.json
Labels: type:enhancement

#1131 fix: don't show gatherings as private in the preview
  lib/depject/gathering/sheet/edit.js
Labels: type:bug
